name: Cities
version: '${project.version}'
main: me.xflyiwnl.cities.Cities
api-version: '1.16'
depend:
  - Vault
softdepend:
  - dynmap

commands:
  city:
  country:
  confirmation:
  invite:
  cities:
