settings:

  board:
    default: "Я люблю Cities"

  time:
    #       hour:minute
    new-day: "24:00"
    format: "dd.MM.yyyy HH:mm"

  economy:
    city-price: 50
    country-price: 100
    land-price: 5

  action-bar:
    default: "#2ee998%city%"

    placeholders:
      spawn-land: " #FCD05C(Дом)"
      sell: " &7 | #ECFDF6Продаётся * #6CE25F%price%$"
      owner: " &7| #2BC983%owner%"

  upkeep:

    city:
      base: 10
      per-land: 1

    country:
      base: 25
      per-city: 2


