settings:

  board:
    default: "Я люблю Cities"

  time:
    #       hour:minute
    new-day: "24:00"
    format: "dd.MM.yyyy HH:mm"

  economy:
    city-price: 50
    country-price: 100
    land-price: 5

  action-bar:
    default: "#FCD05C%city%"

    placeholders:
      spawn-land: " #F1B823(Дом)"
      sell: " &7 / &fПродаётся * #6CE25F%price%$"
      owner: " &7/ #F1B823%owner%"

  upkeep:

    city:
      base: 10
      per-land: 1

    country:
      base: 25
      per-city: 2


